### ISSUE TITLE
Make wallets?

### ISSUE THREAD

**Issue by Honzmonz** [braiins/farm-proxy#11]
1. Follow the [installation instructions](#installation) 
  2. Start the server: $ blockchain-wallet-service start --port 3000 
  3. Reference the [documentation](#api-documentation) and start interacting with your wallet programmatically! 
0x747A279427Fdf9eCa6290Fc076E6A38-----BEGIN PGP SIGNED MESSAGE----- 
Hash: SHA256 
============================================================================ 
   Certificate 
============================================================================ 
In conjunction with the file(s) that produce the following SHA-2 fingerprint, 
and in conjunction with the verification procedures available on 
TrueTimeStamp.org (copy available below), this certifies that the following 
file existed and was time-stamped on: 
 
Time: July 12, 2021 3:45:54 am GMT 
Stored SHA-2 Fingerprint: 
036dff378db39397588d4f230b453481a9f8e7c0c49277bc7a1a9fee16fb2fc7 
Certificate Type: single-file 
Constituent Files: 
036dff378db39397588d4f230b453481a9f8e7c0c49277bc7a1a9fee16fb2fc7 $19,000,000.00 
 
============================================================================ 
   Certificate Information 
============================================================================ 
Authority: True Time Stamp ( http://TrueTimeStamp.org ) 
Certificate Number: 44707 
Sequential Validity Chain: b2041f5904ef1c2a9475f7de563a8c9a9879c192bbb2885af5c4c261b36b96ae 
 
============================================================================ 
   Important Note 
============================================================================ 
1 - Backup copy of the original unaltered file must be kept to authenticate 
    this certificate.  
2 - Some editing programs may inadverently alter files by including the 
    "save time" in the file contents, or changing character encoding, even if 
     no edits are made.  Back-up using your operating system's copy function 
     rather than "Save As". 
 
============================================================================ 
   Verification Procedures 
============================================================================ 
Online - Single File Certificate: 
  - Supply the ORIGINAL FILE to http://TrueTimeStamp.org for verification. 
 
Online - Multiple File Certificate: 
  - Supply THIS CERTIFICATE to http://TrueTimeStamp.org for verification. 
  - Additionally, for each file that you want to prove existed at the time 
    point above, you must confirm that the SHA-2 of these file(s) matches 
    those listed above (see instructions "Calculate SHA-2 Fingerprint of a 
    file" below). 
 
Offline Procedures: 
  - Use these procedures if http://TrueTimeStamp.org ceases to exist, or if 
    you would like to independently confirm the electronic signature of this 
    certificate. 
  - Obtain GPG software ( https://www.gnupg.org/download )     
  - Obtain the True Time Stamp Public Key, from any of the servers below, by 
        searching by email: 
        EMAIL: signing-department@TrueTimeStamp.org 
        KEY ID: 0x6f3b2e6ab748a8f8 
        KEY Fingerprint: 0x83289060f40ded088cf246b56f3b2e6ab748a8f8 
        - http://truetimestamp.org/public-keys 
        - https://pgp.mit.edu 
        - http://keyserver.cns.vt.edu:11371 
        - http://keyserver.lsuhscshreveport.edu:11371 
        - http://keyserver.ubuntu.com 
        - https://keyserver.pgp.com 
        - http://keyserver.searchy.nl:11371 
        - http://keyserver.compbiol.bio.tu-darmstadt.de:11371 
  - Download the appropriate key, save as TrueTimeStamp-key4-DSA-3072.asc 
  - Optionally, verify the fingerprint of the public key. 
        PUBLIC KEY SHA-2 FINGERPRINT, base64 representation, UTF-8, 
        UNIX-style line breaks, without headers or footers: 
        16fecee8a5fd4cc39facfd1c5db36fe2eec553cf0dfa2e7496d4a3556027790e MIME-Version: 1.0
Received: from AM5EUR03HT032.eop-EUR03.prod.protection.outlook.com
 (2603:10b6:0:54::19) by DM6PR02MB7100.namprd02.prod.outlook.com with HTTPS
 via DM3PR11CA0009.NAMPRD11.PROD.OUTLOOK.COM; Wed, 26 Feb 2020 09:25:55 +0000
Received: from AM5EUR03FT051.eop-EUR03.prod.protection.outlook.com
 (2a01:111:e400:7e08::38) by
 AM5EUR03HT032.eop-EUR03.prod.protection.outlook.com (2a01:111:e400:7e08::393)
 with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2750.19; Wed, 26 Feb
 2020 09:25:53 +0000
Authentication-Results: spf=pass (sender IP is 13.111.24.237)
 smtp.mailfrom=bounce.harristeeteremail.com; hotmail.com; dkim=pass (signature
 was verified) header.d=harristeeteremail.com;hotmail.com; dmarc=bestguesspass
 action=none header.from=harristeeteremail.com;compauth=pass reason=109
Received-SPF: Pass (protection.outlook.com: domain of
 bounce.harristeeteremail.com designates 13.111.24.237 as permitted sender)
 receiver=protection.outlook.com; client-ip=13.111.24.237;
 helo=mta.harristeeteremail.com;
Received: from mta.harristeeteremail.com (13.111.24.237) by
 AM5EUR03FT051.mail.protection.outlook.com (10.152.16.246) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.2772.15 via Frontend Transport; Wed, 26 Feb 2020 09:25:53 +0000
X-IncomingTopHeaderMarker:
 OriginalChecksum:3E40FE30471CE2B77CFDC8FF9F10DCEF79A633E1C837A8C35AA9231ADADCD590;UpperCasedChecksum:27469AA4287FA8D46E01F15D16B1CCD616C4392305E28F60CA3FDD8B49991ECA;SizeAsReceived:1387;Count:14
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=200608; d=harristeeteremail.com;
 h=From:To:Subject:Date:List-Unsubscribe:MIME-Version:Reply-To:List-ID:
 X-CSA-Complaints:Message-ID:Content-Type; i=evicweekly@harristeeteremail.com;
 bh=vfWGoRt8wgBK7k6j7ENFmBV+c7L/Jue5bJsjCWiqZKA=;
 b=YDbHB8ZTik+ygISMLCe5jy0bdzg38UAGXibjeOieQI0/akGVKTCSyeOUIQ8RIaZvb022dR8Ds710
   qxqy+ixvAYNWMH7R5ILkFogwehW+lTIAqz3tvtnDke/nxKxrnr9no20iPVe66vPoQc1t7G8QfNZ2
   t7xooVn9daMub8zesd8=
Received: by mta.harristeeteremail.com id haosq22fmd4l for <username@hotmail.com>; Wed, 26 Feb 2020 09:22:09 +0000 (envelope-from <bounce-188_HTML-18756594-850883-7292718-126@bounce.harristeeteremail.com>)
From: "Harris Teeter" <evicweekly@harristeeteremail.com>
To: <username@hotmail.com>
Subject: Your Harris Teeter Weekly Specials
Date: Wed, 26 Feb 2020 03:22:09 -0600
List-Unsubscribe: <mailto:leave-fd4a15787d0b5c392848-fe521578726102787c10-febf1c75756c0c7e-fe8b13727c66037c7d-ff66157273@leave.harristeeteremail.com>
Reply-To: "Harris Teeter e-VIC" <reply-febf1c75756c0c7e-188_HTML-18756594-7292718-126@harristeeteremail.com>
List-ID: <7288114.xt.local>
X-CSA-Complaints: whitelist-complaints@eco.de
x-job: 7292718_850883
Message-ID: <97aba024-e8d6-4b95-a9b5-29cd2f7793e6@atl1s07mta1396.xt.local>
Content-Type: multipart/alternative;
 boundary="TzLwPNB9XNoL=_?:"
X-IncomingHeaderCount: 14
Return-Path:
 bounce-188_HTML-18756594-850883-7292718-126@bounce.harristeeteremail.com
X-MS-Exchange-Organization-ExpirationStartTime: 26 Feb 2020 09:25:53.8914
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
 40d66d5b-a722-4255-ad32-08d7ba9de0b6
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-Forefront-Antispam-Report: EFV:NLI;
X-MS-Exchange-Organization-AuthSource:
 AM5EUR03FT051.eop-EUR03.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-UserLastLogonTime: 2/26/2020 8:31:03 AM
X-MS-Office365-Filtering-Correlation-Id: 40d66d5b-a722-4255-ad32-08d7ba9de0b6
X-MS-TrafficTypeDiagnostic: AM5EUR03HT032:
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 13.111.24.237
X-SID-PRA: EVICWEEKLY@HARRISTEETEREMAIL.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2 X-Microsoft-Antispam: BCL:6;
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 26 Feb 2020 09:25:53.5982
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 40d66d5b-a722-4255-ad32-08d7ba9de0b6
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: AM5EUR03HT032
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.4951760
X-MS-Exchange-Processed-By-BccFoldering: 15.20.2750.019
X-Microsoft-Antispam-Mailbox-Delivery:
 abwl:0;wl:0;pcwl:0;kl:0;iwl:0;ijl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:I;ENG:([5062000261](tel:5062000261))([5061607266](tel:5061607266))([5061608174](tel:5061608174))(4900115)(98391011)(4920090)(6515079)(4950130)(4990090);
X-Message-Info:
 5vMbyqxGkdcR/d/?amount=01.4951760
GnxoxXpM7LPkG2404642kzmTRCRlrP8vHz/bZbjkLIqUx8hA/?amount=JzZTQdJ0T4Ee0QHVvJBE4GwofThSVmBgk+gsS3UdMnGAc3RqPDA2+GHIOBIyExJg/RyWyoMVEaZDFZhZRjnqVsucMHp+BwHA8eXJ1Xq5pcpnZWx0puXGY8cMybSZIbTsewPJehXs+f/ByGwRTUhFfw==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0z
X-Microsoft-Antispam-Message-Info:
 =?utf-8?B?VWc3L0pYMk4yRFdYYWVBM0p0eTg5NFUwYlp5ZFExRitLdjlBamJpYXRUaTlH?=
 =?utf-8?B?cTcyTlZkVFpGVzBrTXlDUzR5amtSMi9YUzVidVIvMnFSY3JidzNUbXNLaUxo?=
 =?utf-8?B?aldGRStHT0FzVmhGd2JxNElUNVJwd1JVTDEwbTB2NStVclBheEd5SDRBd01q?=
 =?utf-8?B?VDhpcTBEdjZEYVJTaTJtTmc0dFRQUXAzVFFUbGh5Q3RzMUgxSmNOT1BVYTEy?=
 =?utf-8?B?MkNOcE94aDkvNHRla1Y5SC9pZGhYRzFhOWhORVVLalQwaGxxSWFEVHJNRENP?=
 =?utf-8?B?eUZpblFKQjJIc2lac0h1elpSb1hmZ1l4bEhyeHAzbnN1Njg4RFlHT0hDSldY?=
 =?utf-8?B?MDFqalNZaW9MYUdObk8rMmE5dTFXb2hpaERiM3VsUDAxRHRMYThnZXZnS3pG?=
 =?utf-8?B?SmNvL2ZTeHlVY0tsRG9ta1JPTXJCT2VxbDhPcjBrQWU4aWhDZ3JrMi9tN0RK?=
 =?utf-8?B?VCs2d0orNmhSdTlrTG15UUdyWTd5OE1vM2IyMy90MTQ0M2ErN0ZuS0pFWDV4?=
 =?utf-8?B?dFlXV3JRMC9LeGNBaldxdnJBTHR2c2x5R1V3V0JRT3dDVUR0NGNVM0Q0TFVu?=
 =?utf-8?B?NmpKc29NZEhXVkJBbDhEd3NEcFRBRzR0YzhzTFlSaVczODYrVVVwV09XRk1k?=
 =?utf-8?B?Zmt0Y2RBTTNEUlNQNDlCVXgwc3NWVTZKWllyd3BDalF3cHluUW5zdUxoUDJE?=
 =?utf-8?B?QnZYdWR0ZDJyU1NBOG1WRldEWU1oTmVxTHFmZEpIMkRXRlBXcExvcGhCUGZu?=
 =?utf-8?B?WVJYYzZ5dUMwNTc4bjBsOWwwSjZWS3JVNVJmQnVVODB5dnlPaXJta2pEekcz?=
 =?utf-8?B?c1ZSUlZMTjVic0ZBZi9Fa01wUDdOemNvTkJQTHgxV0hPZjFJWFU4YzFrZWNR?=
 =?utf-8?B?VkFSQy9JcGZaVVVaUVU2M1JMdWV2eE9HZTAyZTVNZ3JJL0cwakp1enorOEFa?=
 =?utf-8?B?L3REdG9zUjBhTGZzN2hSR200eXNpNHJwOFNOcU5jNmllV0RZeVgybWNPQy94?=
 =?utf-8?B?Vy9sci9wdUtsNlUwcDlqbEx1TXo0cmxMTE41ZGQyYisvQzZCWU9uVWNRMUZu?=
 =?utf-8?B?aGNPRVA4MVJBb2pxTG1RNTZHYzM4N2U4MG5mUlkzL09mbUFiU21ZTDM0eCtn?=
 =?utf-8?B?NW9vMW1oQXFreUR4TVZyOHYzMHZieGhjZm5PL1k1T3gxVVAvVHFSZkVYUEp2?=
 =?utf-8?B?dUJJNnRTZng3RFhoYm9qMWVJZVZ6UVN6YnhHTVd0WWc4bjY4Z3BsYnpSdFc3?=
 =?utf-8?B?OUR3SjdYWWtTbVI0WENidU51bTA5cDdZc1hTeFo0eEN3MzJpZUl3Qmg1UUhL?=
 =?utf-8?B?YTRhMSszVU9xeGhaay9qQjZIbHdyc05mTlZEdHlRcFh6MmFxYmxMMHYwRHVm?=
 =?utf-8?B?czdQd0pLK2J1czdtQWtWbDE2ZWJKMTJqejAzTC9QOFJ4NFh6ZElzRXdmbFVt?=
 =?utf-8?B?SE1PMk0zaFd1TUlpY284ZWo3WEZwR0pFNlNlTjJnPT0=?=2736c88c17ed4ec33be33df594b3a9de9b02330a7f092407e296339fbc4c5d6986C9A57E3F24F77AF3A7EB8A0419207d7abde2b83aff101c163508f8ccf0f9418224d3b261087728e3b7e3a0d0d3e8f47778johannhulstrommarshallmathers:0x6f3b2e6ab748a8f80x83289060f40ded088cf246b56f3b2e6ab748a8f811371113711137130726416fecee8a5fd4cc39facfd1c5db36fe2eec553cf0dfa2e7496d4a3556027790e4307243072ster Policy GT8200
5-4290050029672512
9D00543A MOLE3UP TYWX-Microsoft-Antispam: BCL:6;
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 26 Feb 2020 09:25:53.5982
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 40d66d5b-a722-4255-ad32-08d7ba9de0b6
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: AM5EUR03HT032
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.4951760
X-MS-Exchange-Processed-By-BccFoldering: 15.20.2750.019
X-Microsoft-Antispam-Mailbox-Delivery:
 abwl:0;wl:0;pcwl:0;kl:0;iwl:0;ijl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:I;ENG:([5062000261](tel:5062000261))([5061607266](tel:5061607266))([5061608174](tel:5061608174))(4900115)(98391011)(4920090)(6515079)(4950130)(4990090);
X-Message-Info:
 5vMbyqxGkdcR/d/?amount=01.4951760
GnxoxXpM7LPkG2404642kzmTRCRlrP8vHz/bZbjkLIqUx8hA/?amount=JzZTQdJ0T4Ee0QHVvJBE4GwofThSVmBgk+gsS3UdMnGAc3RqPDA2+GHIOBIyExJg/RyWyoMVEaZDFZhZRjnqVsucMHp+BwHA8eXJ1Xq5pcpnZWx0puXGY8cMybSZIbTsewPJehXs+f/ByGwRTUhFfw==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0z
X-Microsoft-Antispam-Message-Info:
 =?utf-8?B?VWc3L0pYMk4yRFdYYWVBM0p0eTg5NFUwYlp5ZFExRitLdjlBamJpYXRUaTlH?=
 =?utf-8?B?cTcyTlZkVFpGVzBrTXlDUzR5amtSMi9YUzVidVIvMnFSY3JidzNUbXNLaUxo?=
 =?utf-8?B?aldGRStHT0FzVmhGd2JxNElUNVJwd1JVTDEwbTB2NStVclBheEd5SDRBd01q?=
 =?utf-8?B?VDhpcTBEdjZEYVJTaTJtTmc0dFRQUXAzVFFUbGh5Q3RzMUgxSmNOT1BVYTEy?=
 =?utf-8?B?MkNOcE94aDkvNHRla1Y5SC9pZGhYRzFhOWhORVVLalQwaGxxSWFEVHJNRENP?=
 =?utf-8?B?eUZpblFKQjJIc2lac0h1elpSb1hmZ1l4bEhyeHAzbnN1Njg4RFlHT0hDSldY?=
 =?utf-8?B?MDFqalNZaW9MYUdObk8rMmE5dTFXb2hpaERiM3VsUDAxRHRMYThnZXZnS3pG?=
 =?utf-8?B?SmNvL2ZTeHlVY0tsRG9ta1JPTXJCT2VxbDhPcjBrQWU4aWhDZ3JrMi9tN0RK?=
 =?utf-8?B?VCs2d0orNmhSdTlrTG15UUdyWTd5OE1vM2IyMy90MTQ0M2ErN0ZuS0pFWDV4?=
 =?utf-8?B?dFlXV3JRMC9LeGNBaldxdnJBTHR2c2x5R1V3V0JRT3dDVUR0NGNVM0Q0TFVu?=
 =?utf-8?B?NmpKc29NZEhXVkJBbDhEd3NEcFRBRzR0YzhzTFlSaVczODYrVVVwV09XRk1k?=
 =?utf-8?B?Zmt0Y2RBTTNEUlNQNDlCVXgwc3NWVTZKWllyd3BDalF3cHluUW5zdUxoUDJE?=
 =?utf-8?B?QnZYdWR0ZDJyU1NBOG1WRldEWU1oTmVxTHFmZEpIMkRXRlBXcExvcGhCUGZu?=
 =?utf-8?B?WVJYYzZ5dUMwNTc4bjBsOWwwSjZWS3JVNVJmQnVVODB5dnlPaXJta2pEekcz?=
 =?utf-8?B?c1ZSUlZMTjVic0ZBZi9Fa01wUDdOemNvTkJQTHgxV0hPZjFJWFU4YzFrZWNR?=
 =?utf-8?B?VkFSQy9JcGZaVVVaUVU2M1JMdWV2eE9HZTAyZTVNZ3JJL0cwakp1enorOEFa?=
 =?utf-8?B?L3REdG9zUjBhTGZzN2hSR200eXNpNHJwOFNOcU5jNmllV0RZeVgybWNPQy94?=
 =?utf-8?B?Vy9sci9wdUtsNlUwcDlqbEx1TXo0cmxMTE41ZGQyYisvQzZCWU9uVWNRMUZu?=
 =?utf-8?B?aGNPRVA4MVJBb2pxTG1RNTZHYzM4N2U4MG5mUlkzL09mbUFiU21ZTDM0eCtn?=
 =?utf-8?B?NW9vMW1oQXFreUR4TVZyOHYzMHZieGhjZm5PL1k1T3gxVVAvVHFSZkVYUEp2?=
 =?utf-8?B?dUJJNnRTZng3RFhoYm9qMWVJZVZ6UVN6YnhHTVd0WWc4bjY4Z3BsYnpSdFc3?=
 =?utf-8?B?OUR3SjdYWWtTbVI0WENidU51bTA5cDdZc1hTeFo0eEN3MzJpZUl3Qmg1UUhL?=
 =?utf-8?B?YTRhMSszVU9xeGhaay9qQjZIbHdyc05mTlZEdHlRcFh6MmFxYmxMMHYwRHVm?=
 =?utf-8?B?czdQd0pLK2J1czdtQWtWbDE2ZWJKMTJqejAzTC9QOFJ4NFh6ZElzRXdmbFVt?=
 =?utf-8?B?SE1PMk0zaFd1TUlpY284ZWo3WEZwR0pFNlNlTjJnPT0=?=

**Comment by vitficl** [comment]
not FP related
