### ISSUE TITLE
FarmProxy Fails to proxy Stratum v1 Workers to Stratum v2 Pool

### ISSUE THREAD

**Issue by praeluceo** [braiins/farm-proxy#13]
Expected Behavior: configuring FP with a Stratum V2 endpoint (Braiins Pool) should permit Stratum V2 mining by all workers behind the proxy, regardless of whether they're using Stratum V1 or Stratum V2, facilitating standardizing a mixed mining environment onto Stratum V2 or operation of legacy miners on modern pool infrastructure without the need to operate against two pool endpoints (and the associated deficiencies of using Stratum V1).

Observed Behavior:
`Err(NotPresent)
2023-01-16T02:40:17.487400Z  INFO farm_proxy: Welcome to Farm Proxy 22.11 (commit-id: f7976df13b2bb3d2a625b30c3fd3077d8e6a04cf, is-dirty=false, additional-commits=false), rev=f7976df13b
2023-01-16T02:40:17.487446Z  INFO farm_proxy: Using configuration file: /conf/farm_proxy.toml
Error: Invalid configuration: `/conf/farm_proxy.toml'

Caused by:
    Stratum V2 is not supported URL for target. Use Stratum V1 address`

Steps to reproduce: Connect a Stratum v1 worker to Farm Proxy via Stratum V1, configure Farm Proxy to mine against a pool's Stratum v2 URL & credentials, observe that miner remains in "waiting for work" state and "docker logs farm-proxy" throws the above error.

If not yet implemented, how close is this functionality to being complete? If it is implemented, does something specific need to be done in the toml file to enable it successfully?

**Comment by vitficl** [comment]
Hello @praeluceo,

you are right, Stratum V2 controller is not implemented in the proxy yet. It is a known feature request, we have it still in a backlog. No ETA yet though. When I have an update, I will let you know.

Best,
Vit

**Comment by Honzmonz** [comment]
Update should be in the curl copy paste it all into subject line and send to your curl nobody else's curl and it will change that and if that doesn't work then it has Togo thru my curl and then no problem I will try and fix now and post diagnostic results

**Comment by Canefis** [comment]
> Update should be in the curl copy paste it all into subject line and send to your curl nobody else's curl and it will change that and if that doesn't work then it has Togo thru my curl and then no problem I will try and fix now and post diagnostic results

Any results?

**Comment by jprchal-braiins** [comment]
We're tracking this issue in internal backlog, but given the V2 general availability there's no reason to add this feature now. Once the situation on the market changes, we will re-evaluate.
