### ISSUE TITLE
possible to assign weight by TH/s rather than percentage?

### ISSUE THREAD

**Issue by evanbaer** [braiins/farm-proxy#6]
Hi,

I am setting up the farm proxy - is there a config setting to assign a speed to a mining pool target? Eg 100 TH/s, etc.

Thanks,
  Evan

**Comment by papampi** [comment]
I dont think thats a good idea, because hash rate fluctuates on pool.
So you have 200 Th/s and split it by 2x100 Th/s, but it goes up and down by a small percent all the time, it may goes to 210 or comes down to 190, how much should FP assign when its at 195 to each target?

**Comment by evanbaer** [comment]
Makes sense -- do I need to change anything to get the aggregation down to
1 rig if I have 5 rigs hashing to the proxy?

My end goal is to send 1 rig = 1 mining pool account (for several accounts)

Thanks,
  Evan
