### ISSUE TITLE
FP Stops after 5 minute

### ISSUE THREAD

**Issue by papampi** [braiins/farm-proxy#7]
Hi
I tested FP on small scale and it was working ok with no problems but when I tried to test it on two containers with 600 miners it keeps stopping after about 5 to 10 minute
[fp_quits.log](https://github.com/braiins/farm-proxy/files/8694416/fp_quits.log)

**Comment by vitficl** [comment]
Hi, it might be a problem with limit on open files in Linux. Could you try please set the limit to `ulimit -n 10000` and let me know if it helps?

**Comment by papampi** [comment]
Thanks 
Will test and report back.

**Comment by vitficl** [comment]
Close #7.
