### ISSUE TITLE
Prometheus volume size 

### ISSUE THREAD

**Issue by mbio16** [braiins/farm-proxy#9]
Hello,

After a while I could not login to Grafana service even the login was right. In a log file I found that HW disk is full. Prometheus service service has filled 100 % of disk capacity. 

In the docker compose file there was limit to automatically delete old data:
```
 - '--storage.tsdb.retention.time=200h'
```
However, disk cap was exceeded before it could erase something.

It would be nice to have an info about data size per miner per day. It would help to do the math for HDD size required. 

I solved the issue by stopping the Prometheus and Grafana service. Erase prometheus volume and docker-compose up. 

The issue did not affect the mining itself. Farm-proxy service was OK.

**Comment by mbio16** [comment]
Logs are not the main problem. Files is just 1 M. Volume for Prometheus is the issue.

I lower `- '--storage.tsdb.retention.time=100h'`

**Comment by vitficl** [comment]
Hello @mbio16,

you can apply `--storage.tsdb.retention.size` to Prometheus in the docker compose. It helps to reduce maximum amount of disk space used by blocks, but it is not covering WAL though.

**Comment by mbio16** [comment]
ok, thank you
